// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelService.Impl.EF;

namespace TravelService.Migrations
{
    [DbContext(typeof(TravelServiceContext))]
    [Migration("20181001200658_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("TravelService.Impl.EF.PersistedLocation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Attributes");

                    b.Property<double?>("Lat");

                    b.Property<double?>("Lng");

                    b.Property<string>("Term");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("PersistedLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
