// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelService.Impl.EF;

namespace TravelService.Migrations
{
    [DbContext(typeof(TravelServiceContext))]
    [Migration("20190908135037_Subscriptions")]
    partial class Subscriptions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("TravelService.Impl.EF.PersistedLocation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Attributes");

                    b.Property<double>("Lat");

                    b.Property<double>("Lng");

                    b.Property<string>("Term");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("PersistedLocations");
                });

            modelBuilder.Entity("TravelService.Impl.EF.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Callback");

                    b.Property<string>("RouteId");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
